# Generated by Django 4.0.3 on 2022-04-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='modified_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='blog',
            name='whoisincharge',
            field=models.CharField(default='', max_length=10),
        ),
    ]
